;(function() {

"use strict";

///////////////////////////////
// Merge JSON
///////////////////////////////

function fix(target, fixer) {
  let newTarget = JSON.parse(JSON.stringify(target));
  newTarget = recursiveFix(newTarget, fixer);
  return newTarget;
}

function recursiveFix(target, fixer) {
  for (var prop in fixer) {
    if (fixer[prop] === '[[removed]]') {
      // remove property
      delete target[prop];
    } else if (fixer[prop] === null) {
      // skip
    } else if (typeof target[prop] === 'undefined') {
      // doesn't exist in source, add the whole thing
      target[prop] = fixer[prop];
    } else if (typeof target[prop] === 'object') {
      // objet or array, pass it on
      target[prop] = recursiveFix(target[prop], fixer[prop])
    } else {
      // not an object, add the value
      target[prop] = fixer[prop];
    }
  }

  return target;
}

///////////////////////////////
// Expedition Selection
///////////////////////////////

const $body = $(document.body);
const $props = $('.cust_prop_input');
const $download = $('.download');
let exp = null;

$body.on('change', 'input[name="expeditions"]', (ev) => {
  const $checked = $('input[name="expeditions"]:checked');
  const id = $checked.data('json-id');
  exp = JSON.parse(document.getElementById(id).textContent);

  $props.each((index, el) => {
    const $el = $(el);
    const property = $el.attr('name');
    const subproperty = $el.data('subprop');
    const parentProperty = $el.data('parentprop');
    let defaultValue = '--';

    const parent = (parentProperty) ? exp[parentProperty] : exp;
    if (parent && ((subproperty && parent[property] && parent[property][subproperty]) || (!subproperty && parent[property]))) {
      defaultValue = (subproperty) ? parent[property][subproperty] : parent[property];
    }

    const $defaultEl = $el.closest('.cust_item').find('.default');
    $defaultEl.text(defaultValue);
  });

  $download.removeAttr('disabled');
  updateDebug();
});

///////////////////////////////
// Expedition Customization
///////////////////////////////

let overrides = null;

function updateProps() {
  overrides = {};
  let hasUpdates = false;

  $props.each((index, el) => {
    const $el = $(el);
    const $row = $el.closest('.cust_item');
    let value = $el.val();
    const property = $el.attr('name');
    const subproperty = $el.data('subprop');
    const parentProperty = $el.data('parentprop');
    let obj = overrides;
    const storageName = 'property-' + property;

    if (value === '') {
      $row.removeClass('filled');
      localStorage.removeItem(storageName);
      return;
    }

    $row.addClass('filled');
    localStorage.setItem(storageName, value);

    if (value === 'true') value = true;
    if (value === 'false') value = false;
    if (/[0-9]+/.test(value)) value = parseInt(value);
    if (/[0-9.]+/.test(value)) value = parseFloat(value);

    hasUpdates = true;

    if (parentProperty) {
      if (typeof overrides[parentProperty] === 'undefined') overrides[parentProperty] = {};
      obj = overrides[parentProperty];
    }

    if (subproperty) {
      if (typeof obj[property] === 'undefined') obj[property] = {};
      obj[property][subproperty] = value;
    }  else {
      obj[property] = value;
    }
  });

  if (!hasUpdates) {
    overrides = null;
  }

  updateDebug();
}

$body.on('input', '.cust_prop_input', updateProps);

//load saved values
$props.each((index, el) => {
  const $el = $(el);
  const property = $el.attr('name');
  let value = localStorage.getItem('property-' + property);

  if (typeof value === 'undefined') return;

  $el.val(value);
});

///////////////////////////////
// Download
///////////////////////////////

// https://stackoverflow.com/questions/3665115/how-to-create-a-file-in-memory-for-user-to-download-but-not-through-server

function download(filename, text) {
  var element = document.createElement('a');
  element.setAttribute('href', 'data:text/plain;charset=utf-8,' + encodeURIComponent(text));
  element.setAttribute('download', filename);

  element.style.display = 'none';
  document.body.appendChild(element);

  element.click();

  document.body.removeChild(element);
}

$download.on('click', () => {
  if (!exp) return;
  const merged = fix(exp, overrides || {});
  download('SEASON_DATA_CACHE.JSON', JSON.stringify(merged, null, 2).replace('{', '{' + "\n" + '  "_generatedBy": "Generated by https://cwmonkey.github.io/nms-expeditions/",'));
});

///////////////////////////////
// Debug
///////////////////////////////

const $toggleDebug = $('.toggle_debug');
const $debug = $('.debug');
const $debugPanel = $('.debug_panel');
const debugOpen = $toggleDebug.text();

$toggleDebug.on('click', toggleDebug);

function toggleDebug() {
  if ($debug.is('.open')) {
    $debug.removeClass('open');
    $toggleDebug.text(debugOpen);
    localStorage.removeItem('debug_open');
  } else {
    $debug.addClass('open');
    $toggleDebug.text($toggleDebug.data('hide-text'));
    localStorage.setItem('debug_open', 1);
  }
}

function updateDebug() {
  $debugPanel.text('// Expedition JSON overrides:' + "\n" + JSON.stringify(overrides, null, 2));
}

if (localStorage.getItem('debug_open')) {
  toggleDebug();
}

///////////////////////////////
// On page load
///////////////////////////////

updateProps();

})();