# Handling Reading
exclude: [Gemfile, run.bat]

name: cwmonkey/nms-expeditions
title: No Man's Sky Expedition Generator
description: Generates SEASON_DATA_CACHE.JSON files so you can customize and play No Man's Sky expeditions and earn their rewards offline anytime.
# repository: cwmonkey/kotir2

# Conversion
# markdown:    kramdown
highlighter: rouge
excerpt_separator: "\n\n\n"

# Outputting
baseurl: /nms-expeditions

sass:
  style: compressed

# Custom
domain: cwmonkey.github.com
url: /nms-expeditions
author:
  name: cwmonkey
  email: monkey@mysmilies.com
plugins_dir:
 - jekyll-github-metadata
